name: 'Douban Sync Action'
description: 'Sync Douban movie marks to JSON file'
author: 'somkanel'

inputs:
  id:
    description: 'Douban user ID'
    required: true
    default: 'somkanel'
  type:
    description: 'Type of data to sync'
    required: false
    default: 'movie'
  format:
    description: 'Output format'
    required: false
    default: 'json'
  dir:
    description: 'Output directory'
    required: false
    default: './data'

runs:
  using: 'docker'
  image: 'Dockerfile'
